apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath-safe
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
      volumeMounts:
        - name: tmp
          mountPath: /tmp
  volumes:
    - name: tmp
      emptyDir: {}